/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    pub fn shift_left(a: ::std::os::raw::c_int, n: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn shift_right(a: ::std::os::raw::c_int, n: ::std::os::raw::c_int)
        -> ::std::os::raw::c_int;
}
